In [1]:
import pandas as pd
import numpy as np

In [3]:
pad = pd.read_csv('lilly_pads.csv', index_col=0)
pad

a      b      c      d      e      f      g      h      i
a  0        1/2  0        1/2  0      0      0      0      0    
b    1/3  0        1/3  0        1/3  0      0      0      0    
c  0        1/2  0      0      0        1/2  0      0      0    
d    1/3  0      0      0        1/3  0        1/3  0      0    
e  0        1/4  0        1/4  0        1/4  0        1/4  0    
f  0      0        1/3  0        1/3  0      0      0        1/3
g  0      0      0        1/2  0      0      0        1/2  0    
h  0      0      0      0        1/3  0        1/3  0        1/3
i  0      0      0      0      0        1/2  0        1/2  0

In [7]:
pad.dtypes

a    object
b    object
c    object
d    object
e    object
f    object
g    object
h    object
i    object
dtype: object

In [14]:
a = 1/2
b = 1/3
c = 1/4
d = 0
pad = pad.replace({' 1/2':a, ' 1/3':b, ' 1/4':c, ' 0':d})
pad.dtypes

a    object
b    object
c    object
d    object
e    object
f    object
g    object
h    object
i    object
dtype: object

In [15]:
pad

a      b         c      d         e      f         g      h  \
a     0        0.5     0        0.5     0      0         0      0       
b  0.333333  0      0.333333  0      0.333333  0         0      0       
c     0        0.5     0      0         0        0.5     0      0       
d  0.333333  0         0      0      0.333333  0      0.333333  0       
e     0       0.25     0       0.25     0       0.25     0       0.25   
f     0      0      0.333333  0      0.333333  0         0      0       
g     0      0         0        0.5     0      0         0        0.5   
h     0      0         0      0      0.333333  0      0.333333  0       
i     0      0         0      0         0        0.5     0        0.5   

          i  
a     0      
b     0      
c     0      
d     0      
e     0      
f  0.333333  
g     0      
h  0.333333  
i     0

In [16]:
pad.dtypes

a    object
b    object
c    object
d    object
e    object
f    object
g    object
h    object
i    object
dtype: object

In [18]:
pad = pad.astype(float)

In [19]:
pad.dtypes

a    float64
b    float64
c    float64
d    float64
e    float64
f    float64
g    float64
h    float64
i    float64
dtype: object

In [20]:
pad

a     b         c     d         e     f         g     h         i
a  0.000000  0.50  0.000000  0.50  0.000000  0.00  0.000000  0.00  0.000000
b  0.333333  0.00  0.333333  0.00  0.333333  0.00  0.000000  0.00  0.000000
c  0.000000  0.50  0.000000  0.00  0.000000  0.50  0.000000  0.00  0.000000
d  0.333333  0.00  0.000000  0.00  0.333333  0.00  0.333333  0.00  0.000000
e  0.000000  0.25  0.000000  0.25  0.000000  0.25  0.000000  0.25  0.000000
f  0.000000  0.00  0.333333  0.00  0.333333  0.00  0.000000  0.00  0.333333
g  0.000000  0.00  0.000000  0.50  0.000000  0.00  0.000000  0.50  0.000000
h  0.000000  0.00  0.000000  0.00  0.333333  0.00  0.333333  0.00  0.333333
i  0.000000  0.00  0.000000  0.00  0.000000  0.50  0.000000  0.50  0.000000

In [32]:
u = np.array([0,0,0,0,1,0,0,0,0])

In [33]:
u


array([0, 0, 0, 0, 1, 0, 0, 0, 0])

In [35]:
result = u.dot(pad**5)

In [36]:
result.shape

(9,)

In [37]:
result

array([0.        , 0.00097656, 0.        , 0.00097656, 0.        ,
       0.00097656, 0.        , 0.00097656, 0.        ])

In [38]:
u.dot(pad**2)

array([0.    , 0.0625, 0.    , 0.0625, 0.    , 0.0625, 0.    , 0.0625,
       0.    ])

In [39]:
u.dot(pad**9)

array([0.00000000e+00, 3.81469727e-06, 0.00000000e+00, 3.81469727e-06,
       0.00000000e+00, 3.81469727e-06, 0.00000000e+00, 3.81469727e-06,
       0.00000000e+00])